version: "3.8"
services:
  avito-tech:
    image: avito-tech-image
    container_name: avito-tech
    build: .
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: avito_db
    ports:
      - "9000:9000"
    depends_on:
      - pgdb
      
  pgdb:
    image: postgres:11
    container_name: avito-tech-postgres
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: avito_db
    ports:
      - "54320:5432"
