version: "3.8"

services:
  balance-service:
    build:
      context: ./
      dockerfile: ./balance-service.dockerfile
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password database=users sslmode=disable timezone=UTC connect_timeout=5"
    restart: always

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    restart: always
    volumes:
      - ./db/data/postgres/:/var/lib/postgresql/data/
